/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradleproject1;
import javax.swing.JOptionPane;

public class App {
    

    public static void main(String[] args) {
        int Creditdays = 30;
        JOptionPane.showMessageDialog(null, " " + Creditdays);
        JOptionPane.showMessageDialog(null, "Every bill is due in " + Creditdays + " days ");
    }
}
